_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  ROI_HEADS:
    NUM_CLASSES: 1
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[16], [32], [64], [128], [256]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0, 4.0, 8.0]]
DATASETS:
  TRAIN: ("funsd_train",)
  TEST: ("funsd_eval",)
SOLVER:
  STEPS: (50000, 100000)
  MAX_ITER: 200000
  # Number of images per batch across all machines.
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 500
  WEIGHT_DECAY: 0.0001


#  Defaults:
#
#  # See detectron2/solver/build.py for LR scheduler options
#  _C.SOLVER.LR_SCHEDULER_NAME = "WarmupMultiStepLR"
#  _C.SOLVER.MAX_ITER = 40000
#  _C.SOLVER.MOMENTUM = 0.9
#  _C.SOLVER.WEIGHT_DECAY_NORM = 0.0
#  _C.SOLVER.GAMMA = 0.1
#  # The iteration number to decrease learning rate by GAMMA.
#  _C.SOLVER.STEPS = (30000,)
#  _C.SOLVER.WARMUP_FACTOR = 1.0 / 1000
#  _C.SOLVER.WARMUP_ITERS = 1000
#  _C.SOLVER.WARMUP_METHOD = "linear"
#
#  # Detectron v1 (and previous detection code) used a 2x higher LR and 0 WD for
#  # biases. This is not useful (at least for recent models). You should avoid
#  # changing these and they exist only to reproduce Detectron v1 training if
#  # desired.
#  _C.SOLVER.BIAS_LR_FACTOR = 1.0
#  _C.SOLVER.WEIGHT_DECAY_BIAS = _C.SOLVER.WEIGHT_DECAY


DATALOADER:
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 500
  DETECTIONS_PER_IMAGE: 10
VIS_PERIOD: 100