_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x/138205316/model_final_a3ec72.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1
  RPN:
    PRE_NMS_TOPK_TRAIN: 100  # Per FPN level
    PRE_NMS_TOPK_TEST: 4  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 10
    POST_NMS_TOPK_TEST: 4
DATASETS:
  TRAIN: ("funsd_train",)
  TEST: ("funsd_eval",)
SOLVER:
  STEPS: (21000, 25000)
  MAX_ITER: 100000
  # Number of images per batch across all machines.
  IMS_PER_BATCH: 2
  BASE_LR: 0.0009
  CHECKPOINT_PERIOD: 500
  WEIGHT_DECAY: 0.0001


#  Defaults:
#
#  # See detectron2/solver/build.py for LR scheduler options
#  _C.SOLVER.LR_SCHEDULER_NAME = "WarmupMultiStepLR"
#  _C.SOLVER.MAX_ITER = 40000
#  _C.SOLVER.MOMENTUM = 0.9
#  _C.SOLVER.WEIGHT_DECAY_NORM = 0.0
#  _C.SOLVER.GAMMA = 0.1
#  # The iteration number to decrease learning rate by GAMMA.
#  _C.SOLVER.STEPS = (30000,)
#  _C.SOLVER.WARMUP_FACTOR = 1.0 / 1000
#  _C.SOLVER.WARMUP_ITERS = 1000
#  _C.SOLVER.WARMUP_METHOD = "linear"
#
#  # Detectron v1 (and previous detection code) used a 2x higher LR and 0 WD for
#  # biases. This is not useful (at least for recent models). You should avoid
#  # changing these and they exist only to reproduce Detectron v1 training if
#  # desired.
#  _C.SOLVER.BIAS_LR_FACTOR = 1.0
#  _C.SOLVER.WEIGHT_DECAY_BIAS = _C.SOLVER.WEIGHT_DECAY


DATALOADER:
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 500
  DETECTIONS_PER_IMAGE: 4
VIS_PERIOD: 100